### ISSUE TITLE
unable to validateSignature

### ISSUE THREAD

**Issue by komthep** [runnables/line-bot-sdk-nodejs#12]
```
TypeError: Not a buffer
at TypeError (native)
at new Hmac (crypto.js:88:16)
at Object.Hmac (crypto.js:86:12)
at Object.exports.validateSignature (/app/node_modules/line-bot-sdk/lib/SignatureValidator.js:8:31)
at Object.api.validateSignature (/app/node_modules/line-bot-sdk/lib/bot.js:78:31)
at /app/server.js:21:34
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at next (/app/node_modules/express/lib/router/route.js:131:13)
at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by nsmag** [comment]
+1

**Comment by komthep** [comment]
Fixed. See cfbbbbef56856d0ef586cc7ad1de27ffc117732c

**Comment by nsmag** [comment]
Test failed with this code:

``` js
var config = {
  channelID: '1441301333',
  channelSecret: 'testsecret',
  channelMID: 'u0a556cffd4da0dd89c94fb36e36e1cdc'
};

var json = {
  result: [
    {
      from: 'u206d25c2ea6bd87c17655609a1c37cb8',
      fromChannel: '1341301815',
      to: ['u0cc15697597f61dd8b01cea8b027050e'],
      toChannel: '1441301333',
      eventType: '138311609000106303',
      id: 'ABCDEF-12345678901',
      content: {
        id: '325708',
        createdTime: 1332394961610,
        from: 'uff2aec188e58752ee1fb0f9507c6529a',
        to: ['u0a556cffd4da0dd89c94fb36e36e1cdc'],
        toType: 1,
        contentType: 1,
        text: 'hello'
      }
    },
    {
      from: 'u206d25c2ea6bd87c17655609a1c37cb8',
      fromChannel: '1341301815',
      to: ['u0cc15697597f61dd8b01cea8b027050e'],
      toChannel: '1441301333',
      eventType: '138311609100106403',
      id: 'ABCDEF-12345678902',
      content: {
        revision: 2469,
        opType: 4,
        params: [
          'u0f3bfc598b061eba02183bfc5280886a',
          null,
          null
        ]
      }
    }
  ]
};

var signature = 'kPXp0nPWSzfWAapWHiesbcztpKnXJoX8krCa1CcTghk=';

it('should be able to validate signature', function(done) {
  SignatureValidator.validateSignature(json, config.channelSecret, signature).should.be.true;
  SignatureValidator.validateSignature(json, config.channelSecret, 'XXX').should.be.false;

  done();
});
```

Result:

```
TypeError: Not a string or buffer
      at TypeError (native)
      at Hmac.Hash.update (crypto.js:70:16)
      at Object.exports.validateSignature (lib/SignatureValidator.js:8:67)
      at Context.<anonymous> (test/testSignatureValidator.js:56:24)
```

**Comment by PanJ** [comment]
@nsmag `SignatureValidator.validateSignature` takes `string` as an input. Could you please provide us the full test file?

**Comment by nsmag** [comment]
@PanJ test code updated above

**Comment by PanJ** [comment]
@nsmag it should be   

``` javascript
SignatureValidator.validateSignature(JSON.stringify(json), config.channelSecret, signature).should.be.true;
SignatureValidator.validateSignature(JSON.stringify(json), config.channelSecret, 'XXX').should.be.false;
```

See https://github.com/runnables/line-bot-sdk-nodejs/blob/master/lib/client.js#L77-L79 for more detail.

**Comment by nsmag** [comment]
Updated test as @PanJ mentioned.
Still broken

```
1) SignatureValidator should be able to validate signature:
     AssertionError: expected false to be true
```

**Comment by nsmag** [comment]
See https://github.com/runnables/line-bot-sdk-nodejs/blob/master/test/testSignatureValidator.js for full test file.

**Comment by PanJ** [comment]
Fixed in https://github.com/runnables/line-bot-sdk-nodejs/commit/e398f382380b68d3b64e3100efa72632f0e911d5
